# Packer template for building Ubuntu Server VM Image

source "proxmox-iso" "ubuntu" {
    proxmox_url                 = var.pm_url
    iso_file                    = "local:iso/ubuntu-24.04.1-live-server-amd64.iso"
    iso_checksum                = "none"
    username                    = var.pm_user
    password                    = var.pm_password
    node                        = var.pm_node
    iso_storage_pool            = var.pm_iso_storage_pool
    vm_name                     = "packer-ubuntu"
    vm_id                        = "200"
    memory                      = 4096
    cores                       = 2
    cpu_type                    = "host"
    sockets                     = 1
    os                          = "l26"
    bios                        = "ovmf"
    machine                     = "q35"
    ssh_username                = var.ssh_user
    ssh_password                = var.ssh_password
    http_directory              = "http"
    insecure_skip_tls_verify    = true
    qemu_agent                  = true
    scsi_controller             = "virtio-scsi-single"
    template_name               = "ubuntu-server-24"
    template_description        = "template generated by packer for ubuntu-server-24"
    cloud_init                  = true
    cloud_init_storage_pool     = var.pm_iso_storage_pool
    unmount_iso                 = true
    disks {
        type = "scsi"
        disk_size = "20G"
        storage_pool = var.pm_storage_pool
        io_thread = true
    }
    network_adapters {
        model       = "virtio"
        bridge      = "vmbr2"
        vlan_tag    = 10
        firewall    = false
    }

}

build {
    sources = ["source.proxmox-iso.ubuntu"]
}

packer {
    required_plugins {
        name = {
            version = "~> 1"
            source = "github.com/hashicorp/proxmox"
        }
    }
}