source "proxmox-iso" "vyos" {
    proxmox_url                 = var.pm_url
    iso_file                    = "local:iso/vyos-1.5-rolling-202407280023-amd64.iso"
    iso_checksum                = "none"
    iso_storage_pool            = var.pm_iso_storage_pool
    unmount_iso                 = true
    insecure_skip_tls_verify    = true
    username                    = var.pm_user
    password                    = var.pm_password
    node                        = var.pm_node
    vm_name                     = "packer-vyos"
    vm_id                       = 501
    tags                        = "vyos;template"
    memory                      = 2048
    cores                       = 1
    cpu_type                    = "host"
    sockets                     = 1
    bios                        = "ovmf"
    machine                     = "pc"
    qemu_agent                  = false
    scsi_controller             = "virtio-scsi-single"
    template_name               = "packer-vyos"
    template_description        = "Template generated by packer for VyOS"
    ssh_username                = var.vyos_user
    ssh_password                = var.vyos_password
    disks {
        type = "scsi"
        storage_pool = var.pm_storage_pool
        disk_size = "10G"
        io_thread = true
    }
    #network_adapters {
    #    model = "virtio"
    #    bridge = "vmbr1"
    #    firewall = true
    #}
}

build {
    sources = ["source.proxmox-iso.vyos"]
}

#packer {
#    required_plugins {
#        name = {
#            version = "~> 1"
#            source = "github.com/hashicorp/proxmox"
#        }
#    }
#}